### ISSUE TITLE
Slack Logging

### ISSUE THREAD

**Issue by baingar** [EsOsO/Logging#10]
Is Slack logging still compatible? I'm having trouble logging messages to Slack. I've verified my URI is proper as I can send a manual Invoke-WebRequest  command to Slack, but not from this Logging module.

**Comment by EsOsO** [comment]
I'm sorry... I don't use slack and the slack part is not maintained, feel free to contribute with a pull request.
Maybe next week I can try to look into the issue. Could you provide me some more info? Also the `Invoke-WebRequest` you used to successfully send a message.

**Comment by baingar** [comment]
I haven't had time to investigate the specific reason. I followed the readme and added logging target by populating only the webhook serverURI. I then performed a write-log and it didn't send the message to slack.

On an unrelated note, is there a capability to log to a specific target when multiple logging targets are added?

**Comment by EsOsO** [comment]
Right now there's no way to log to a specific target if multiple are defined; you could try using `Add-LoggingLevel` and define a custom level used only in a target:

```
Add-LoggingLevel -Level 5 -LevelName CUSTOM
Add-LoggingTarget -Name Slack -Configuration @{ServerUri='<slack channel url>'; Level='CUSTOM'}
Write-Log -Level CUSTOM -Message 'Hello, World!'
```

I'll try to look into the issue of the target; I'll keep you posted.

**Comment by EsOsO** [comment]
I fixed the issue. 51e17be8d1aeb5541a71fc9f97a9cd96e259ddee

Let me know if you still have issues.

**Comment by baingar** [comment]
Awesome! Thank you. I'll have to give it another try and let you know how it works. Cheers!
