### ISSUE TITLE
Are target names case sensitive?

### ISSUE THREAD

**Issue by mabster** [EsOsO/Logging#106]
If I run the following commands with the latest module version, I get an error:

```
PS>Add-LoggingTarget -Name console
PS>Write-Log -Level INFO 'hello'

Level not a valid integer or a valid string:
```

If I use `Console` with a capital C when adding the target, everything's fine.

I don't think the -Name parameter for Add-LoggingTarget should be case sensitive, so something strange is happening here.

**Comment by EsOsO** [comment]
You'r right, `Target` name is case sensitive right now due to how PSCustomObject match key names.

**Comment by mabster** [comment]
This is fixed now! Thanks Tadas. I will close this issue.
