### ISSUE TITLE
File Target is converting $Log.body to json permanently

### ISSUE THREAD

**Issue by kilale** [EsOsO/Logging#112]
In Target "File" Line 19 the variables content is converted to json, which is fine to write it to file.
But the current code is alternating the $Log.Body permanently to json, which is causing major issues on other Targets like Teams. In Target "Teams" the prior Body as hashtable is now a json formatted string, which is not handled within the Body section code. 
Could you please change the code in Target "File" Line 19 to save the json as a different variable?

**Comment by EsOsO** [comment]
Fixed in the latest release
