### ISSUE TITLE
How to use Set-LoggingDefaultLevel?

### ISSUE THREAD

**Issue by moggoly** [EsOsO/Logging#14]
Hi,

I might be using this wrong, but I can't seem to get the default level set. My understanding is that if I call Set-LoggingDefaultLevel, then I shouldn't need to specify Level on calls to Write-Log, however Level is a mandatory parameter on Write-Log. I would expect Write-Log to be interrogating the default value I'm setting, and use that on all subsequent calls.

Or is my understanding incorrect?

Mike.

**Comment by moggoly** [comment]
Ignore this issue - I'm understanding the purpose of Set-LoggingDefaultFormat now - it's used to define the minimum level that should be sent to the targets.

**Comment by EsOsO** [comment]
Glad you found out, I was about to reply. Feel free to ask if something isn't clear in the doc.
