### ISSUE TITLE
Add-LoggingTarget randomly fails to load custom targets

### ISSUE THREAD

**Issue by jeremymcgee73** [EsOsO/Logging#15]
I have been troubleshooting a issue where sometimes Add-LoggingTarget randomly fails to load custom targets. However, if I add my custom target into the Target folder for the module, I do not have this issue. I used Get-LoggingTargetAvailable to test to see if the target was loaded, and it was. The issue is very intermittent.

This is the error:

    powershell.exe : Add-LoggingTarget : Cannot validate argument on parameter 'Name'. The argument 
    At line:3 char:5
    +     & powershell -NonInteractive -executionpolicy bypass -file C:\scr ...
    +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : NotSpecified: (Add-LoggingTarg.... The argument :String) [], RemoteException
        + FullyQualifiedErrorId : NativeCommandError
     
    "Gelf" does not belong to the set "Email,Console,ElasticSearch,File,Slack" 
    specified by the ValidateSet attribute. Supply an argument that is in the set 
    and then try the command again.
    At C:\scripts\Test-Import\Test-Import.ps1:22 char:29
    +     Add-LoggingTarget -Name Gelf -Configuration @{
    +                             ~~~~
        + CategoryInfo          : InvalidData: (:) [Add-LoggingTarget], ParentCont 
       ainsErrorRecordException
        + FullyQualifiedErrorId : ParameterArgumentValidationError,Add-LoggingTarg 
       et

**Comment by EsOsO** [comment]
I'm inspecting the issue, could you provide me an example of the script you're trying to run?

**Comment by EsOsO** [comment]
I'll close the issue cause i've got no response from @jeremymcgee73. Reopen if you need.

**Comment by jeremymcgee73** [comment]
I finally came back to this. I have figured out how to alteast reproduce the problem. I believe that the path or files set in "Set-LoggingCustomTarget" are locked when multiple PowerShell processes are using the logging module. I have created a test custom target that you can test with. [Test-Logging](https://github.com/jeremymcgee73/PowershellScripts/tree/master/Test-Logging).

 `'1 .. 100 |% { powershell -file "C:\scripts\Test-Logging\test.ps1"}'`. But, you must run this in two separate consoles before it will error. Thanks so much for your help! I also have a screenshot of the error in the repo. Thanks again!
