### ISSUE TITLE
Add-LoggingTarget fails to load custom targets when multipe processes are running.

### ISSUE THREAD

**Issue by jeremymcgee73** [EsOsO/Logging#20]
I opened a issue about this before but I was 100% sure how to reproduce the issue.  I believe that the path or files set in "Set-LoggingCustomTarget" are locked when multiple PowerShell processes are using the logging module. I have created a test custom target that you can test with. [Test-Logging](https://github.com/jeremymcgee73/PowershellScripts/tree/master/Test-Logging).

If you download the example I created above, you can run the following command to test. But, to have a failure you will need to be running this command in two separate consoles. I have also included a screenshot of the error in the repo.
 `'1 .. 100 |% { powershell -file "C:\scripts\Test-Logging\test.ps1"}'`. 

Thanks so much for your help!

**Comment by jeremymcgee73** [comment]
Also, it must be timed correctly. To repeat it, sometimes I would just run this command in 10 different consoles, until it started to happen.

**Comment by jeremymcgee73** [comment]
I did some more troubleshooting this morning. If I put the custom test target in the target folder, inside the module, the error doesn't occur. I think this will be my temporary fix/workaround.

**Comment by EsOsO** [comment]
Hi @jeremymcgee73, thanks for pointing out this issue, it lacks a call to `Initialize-LoggingTarget` inside the function `Set-LoggingCustomTarget`

**Comment by jeremymcgee73** [comment]
Thank you!
