### ISSUE TITLE
Ability to specify number of log files to keep in File target

### ISSUE THREAD

**Issue by renehernandez** [EsOsO/Logging#23]
It would be desirable to have an option to set the maximum number of log files to keep while configuring the File target.
And whenever a new log file is created the oldest one can be deleted. Something similar to what log4net does with [RollingFileAppender](https://logging.apache.org/log4net/release/sdk/html/T_log4net_Appender_RollingFileAppender.htm)

**Comment by EsOsO** [comment]
Hi @renehernandez, I need to rework some logics before adding this request; right now I've tested some rolling function called every time a log is written but the performance are very bad.

Maybe I can think some sort of initializiation on the target, but in that way the roll will take place only the first time the script executes.
I will look into something, if you have any suggestion feel free to post it.

**Comment by renehernandez** [comment]
Hi @EsOsO, I am interested in contributing to these feature. I went over the code, but couldn't find any rolling functionality here. Are you planning to share what you currently have? Otherwise, I  could start developing some prototype as well for the rolling functionality by myself, but it would be wise to discuss some design upfront.

**Comment by EsOsO** [comment]
I'm thinking about adding an `Init` scriptblock to the targets that gets executed once you `Add-LoggingTarget`. In this way we have an entry point to execute code only during Logging setup hence the ability to rotate log files and clean the containing folder.

**Comment by tosoikea** [comment]
Any further thoughts or progress on implementing the log rotating?
If not I could have a look by the end of this week.

**Comment by renehernandez** [comment]
@tosoikea I didn't get to do any progress on this, so feel free to chime in

**Comment by EsOsO** [comment]
I'm sorry guys, I'm busy at work so don't have much time to code. Hope to get back asap

**Comment by allen-chin** [comment]
Just want to double-check with everyone about the status of this issue. Would it be okay if I took a look to try something out?

**Comment by EsOsO** [comment]
Sure, no problem, feel free to submit a PR

**Comment by tosoikea** [comment]
@EsOsO As this thread seems to be falling asleep. I started work on it. I am implementing the following criterias for rotation

1. RotateAfterAmount
   After a given threshold of files is exceeded, oldest first
2. RotateAfterDate
   All files exceeding a certain difference between the current date and their creation time
3. RotateAfterSize
   All files exceeding a certain size in bytes

The normal behaviour is going to be, that those files are discarded. However, there is also going to be an option to specify CompressRotated to put them into a .zip (or equivalent).

**Comment by tosoikea** [comment]
@EsOsO I coded a first implementation on https://github.com/tosoikea/Logging/tree/rotation. Looking forward to your feedback. :)
