### ISSUE TITLE
Write-log no simple call

### ISSUE THREAD

**Issue by lesodtc** [EsOsO/Logging#26]
Hello,
I tested your module on Windows 10 , PS 5.1 , is very famous! 

But I can call Write-Log without Level parameter, on documentation , it's possible. Can you give me an exemple ? 
If I give a level each time, it's fine. But it's not very beautiful when you read code.

KR 
Damien

**Comment by EsOsO** [comment]
Hi @lesodtc, I think that setting a default level doesn't beautify the code, it could be useful thou for oneliners or short scripts. I'll look into the request by the way.
