### ISSUE TITLE
Ability to view output of Invoke-RestMethod in ElasticSearch target

### ISSUE THREAD

**Issue by M1kep** [EsOsO/Logging#28]
Is there any way to get the output of invoke-restmethod in the ElasticSearch target? I can't seem to find a way to get anything out of that as it is a loaded script block. I've resorted to writing to a file for debugging from within a custom target. What's the recommended method of troubleshooting those calls?

**Comment by EsOsO** [comment]
Hi @M1kep, I think the best way to troubleshoot the calls is what you are already doing. I too use an `Out-File` call to debug sometimes.
