### ISSUE TITLE
Logging to specific target

### ISSUE THREAD

**Issue by MCrank** [EsOsO/Logging#33]
Hello.  I have two targets configured, File & Slack.  Poking around it does not look as though you can target a specific Write-Log message to a particular Target.  i.e I have some monitoring built into a script that should fire a Slack message only when certain criteria are met.  I tried the setup specified in Issue #10 but All of the log messages got fired into the slack channel but were identified as the correct level. 

Wondering if there are plans to allow this or if there is a different configuration along the lines of below that will allow only specific messages to hit the Slack channel.
```
Add-LoggingLevel -Level 5 -LevelName SLACK
Add-LoggingTarget -Name Slack -Configuration @{ServerUri='<slack channel url>'; Level='SLACK'}
Write-Log -Level SLACK -Message 'Bad Stuff Happening'
```

Thank you

**Comment by Tadas** [comment]
You might want to try using a higher level for your loglevel (eg. 50).

Log messages are processed by targets if their level is equal to or higher than that of the target
https://github.com/EsOsO/Logging/blob/e62cd0b185588972bce7731c05aa9359effe456d/Logging/Logging.psm1#L102-L104

Your config sets Slack to receive all messages that are higher than 5, which is essentially log messages:
https://github.com/EsOsO/Logging/blob/e62cd0b185588972bce7731c05aa9359effe456d/Logging/Logging.psm1#L3-L7

**Comment by MCrank** [comment]
Ahh.  That makes sense.  I'll give that a shot.  Thank you

**Comment by MCrank** [comment]
@Tadas @EsOsO That fixed my issue.  Thank you for the response!
