### ISSUE TITLE
Remove Start-Sleep from Logging.psm1

### ISSUE THREAD

**Issue by tosoikea** [EsOsO/Logging#42]
Inside Logging.psm1 the consumer of the message queue only consumes messages every  10ms. 
L 109 : Start-Sleep -Milliseconds 10

This leads to two problems : 
1. Unecessary cpu usage
2. Missing messages
   2.1 Partly resolved through Wait-Logging => Enforces unecessary delay

Request : 
Proper Producer-Consumer with Wait and Pulse. (Thread only works when new messages are laid into the queue)

**Comment by EsOsO** [comment]
You're right, it's the part I like less of my code. If you have any suggestion about how to implement a producer-cosumer pattern I'll be glad to discuss about it, I don't, actually, know how to remove that sleep, I also tried removing threading at all, but the concept of delegating the writing of the log to a thread it's appealing imho.

Feel free to suggest whatever you consider helpful to the project.

**Comment by tosoikea** [comment]
@EsOsO I completly agree that it is very important to keep the concept of delegating the produced logging messages to a consumer running in a separate thread. 

I will try to look over the implementation in detail till to tomorrow and try to remove the dependency on  Start-Sleep.

**Comment by EsOsO** [comment]
@tosoikea, did you ever lost messages? I'm using the module quite extensively at work, but never had such issue. Just curios...

**Comment by tosoikea** [comment]
@EsOsO As long as Wait-Log is called, messages should obviously never get lost. 
But you will notice the delay enforced into the logging by only having Console as LogTarget and then writing logs. 

We are planning on using this module for logging at our work and with a high grade of automation we want to limit the possibilities of any kind of errors. (or wasted resources)

**Comment by EsOsO** [comment]
I completely agree about wasted resources (the module is working fine for me using in production, but is far from efficient). 
Regarding delay, yes, there's delay about the "main script" execution and the console line written and that's why I introduced `Wait-Logging` to be used in scheduled/unattended scripts to avoid that the "main scripts" ends without emptying the log queue (a way to flush log before script ends).

**Comment by renehernandez** [comment]
@EsOsO @tosoikea I have run into the situation of forgetting to place `Wait-Logging` at the end of a couple of scripts a few times in some part of our automation at work :(!! The experience is good because it always take a while to realize that I am missing to place the `Wait-Logging` call at the end. I think from a user experience it would be better if we could get rid of it completely

**Comment by EsOsO** [comment]
@renehernandez totally agree, it should be an implicit call.

**Comment by tosoikea** [comment]
I implemented a first sketch of a working implementation in my fork.
Feel free to have a look. 
I am going to test further and improve the overall code structure.

(I have a requires version 5.0 for the using directive. This can be removed for better compatibility)

**Comment by EsOsO** [comment]
Nice approach, didn't know about BlockingCollection.
How is working the module with this changes?

**Comment by tosoikea** [comment]
It seems to behave quite well. I am going to write some tests to ensure functionality.
Also the need for Wait-Logging should pretty much be removed.

**Comment by EsOsO** [comment]
Great work. Can't wait to test it out ;)

**Comment by tosoikea** [comment]
I had some free time today and yesterday and pushed a fully functional version to my fork.
I am not going to convert it to a pull request, as i want to further test functionality.

If you have the time to test the implementation, I would be very happy. :>

**Comment by EsOsO** [comment]
Yeah, I'm trying to better understand RunspacePool cause, right now, we are not using throttling (we spawn only 1 thread). I'm experimenting with a runspace that act as a QueueManager that loop over the BlockingCollection with the idea to use a runspacepool with threads == to the number of active targets (not sure if it's a good idea, still figuring it out).

I'll keep you posted if I make any progression on this way

PS do you how if there's a way to profile the execution time to see difference in implementation?

**Comment by EsOsO** [comment]
Just tested out your implementation, it's amazing!! The execution speed of the "main script" is quite the same, but console writing is synced with the "main flow".

Great job!

**Comment by renehernandez** [comment]
> PS do you how if there's a way to profile the execution time to see difference in implementation?

@EsOsO A simple approache would be either use `Measure-Command` or an `Stopwatch` instance to calculate the average time of several runs of tests

**Comment by tosoikea** [comment]
I just created the corresponding pull request.
As a side note : 
- One consumer thread should be enough for every local action. (Speed is high enough, Threads just add unecessary overhead)
- We could look into further multithreading when doing tasks resulting network (elasticsearch...) traffic

**Comment by EsOsO** [comment]
I've pushed to dev some changes, pls take a look and if ok I'll close the issue and publish a major version (3.0.0) of the module

**Comment by tosoikea** [comment]
I will be taking a look this evening.

**Comment by tosoikea** [comment]
@EsOsO Everything seems to be working quite well. I am not going not have a lot of free time this week, but will add further tests and documentation as soon as possible.

**Comment by EsOsO** [comment]
closed in 24a715ec55cbd171338ab84b07d38444974bfe61
