### ISSUE TITLE
Memory leak in version 2.10.0

### ISSUE THREAD

**Issue by romanlum** [EsOsO/Logging#47]
I always use the latest version of the module and since 4 days my build was slow as hell and even failed.
I tried everything to fix it, but nothing worked.

I saw that the memory of the  powershell.exe process grew to 7 GB and more and i checked all modules and saw that 2.10.0 was released 4 days ago :)

After downgrade to module version 2.9.1 my build worked as before and  no significat memory increase was observed.
So there might be a problem in module version 2.10.0

**Comment by zach72** [comment]
I am able to reproduce this with the example in the docs:
```

function Write-CustomLog {
    [CmdletBinding()]
    param(
        $Level,
        $Message
    )

    Write-Log -Level $Level -Message $Message
}

function Invoke-CallerFunctionWithCustomLog {
    Add-LoggingTarget -Name Console -Configuration @{Level = 'DEBUG'}
    Set-LoggingDefaultFormat -Format '[%{filename}] [%{caller}] %{message}'

    # Set the scope to find the caller information from
    Set-LoggingCallerScope -CallerScope 2

    1..5 | ForEach-Object {
        # In this example, during execution of Write-Log the numeric scope represents the following:
        # 0 - Write-Log scope
        # 1 - Write-CustomLog scope (which would be default value)
        # 2 - Invoke-CallerFunctionWithCustomLog
        Write-CustomLog -Level (Get-Random 'DEBUG', 'INFO', 'WARNING', 'ERROR') -Message 'Hello, World! (With caller scope at level 2)'
    }
}

Invoke-CallerFunctionWithCustomLog
```

This doesn't work as intended, as the logging format doesn't match what is set with the Set-LoggingDefaultFormat command.

**Comment by EsOsO** [comment]
I'm currently not able to reproduce the memory leak in 2.10.0, using the example above my powershell.exe uses 189Mb of RAM. I'll inspect deeper asap, meanwhile you can downgrade to 2.9.1 or try the alpha build of the upcoming 3.0.0 release (you won't be disappointed ;) )

**Comment by EsOsO** [comment]
Released new version, memory leak should be resolved.
