### ISSUE TITLE
Removing Module prevents the pending logs from writing.

### ISSUE THREAD

**Issue by mcvic1rj** [EsOsO/Logging#5]
IF you remove the module or close the powershell session, the events waiting to be written are not logged.

This comes up when using a scheduled task and the script finished before the running. 

example:

if (!(Get-Command -Name Write-log))
{
    Import-Module logging
}
$Logging.Targets += @{
    File = @{
        Path        = "c:\logs\%{+%Y%m%d}1.log"    # <Required> Sets the file destination (eg. 'C:\Temp\%{+%Y%m%d}.log') 
    }
}

foreach ( $a in 1..1000){Write-Log -Level DEBUG -Message $a}
Remove-Module logging

**Comment by EsOsO** [comment]
Yes, you are right @mcvic1rj, it's was fixed in 93eb200fc77c831e7b6ac053544f16273ba408e0.

You can end your script with Wait-Log and remove the module, in this way you'll be sure to empty the log message queue.

Thanks

**Comment by mcvic1rj** [comment]
What about putting wait log in the on remove part of the psm1 file?

-
Ryan




On Tue, Jun 14, 2016 at 7:02 AM -0400, "Massimo Bonvicini" <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes, you are right @mcvic1rj<https://github.com/mcvic1rj>, it's was fixed in 93eb200<https://github.com/EsOsO/Logging/commit/93eb200fc77c831e7b6ac053544f16273ba408e0>.

You can end your script with Wait-Log and remove the module, in this way you'll be sure to empty the log message queue.

Thanks

-

**Comment by EsOsO** [comment]
As far as I know `$ExecutionContext.SessionState.Module.OnRemove` it's called only on `Remove-Module` and not when the shell exit.

I found [System.Management.Automation.PsEngineEvent]::Exiting that seems promising, I'll make some tests.

**Comment by EsOsO** [comment]
Fixed in a79daeb55c2fa3ae58e30b6f9869d81599a058bc
