### ISSUE TITLE
Support for powershell core

### ISSUE THREAD

**Issue by jasonchester** [EsOsO/Logging#54]
powershell core does not support apartment states. 

Checking for powershell edition -eq Desktop prior to setting the Apartment state would prevent this error.

```sh
The property 'ApartmentState' cannot be found on this object. Verify that the property exists and can be set.
At /Users/jason.chester/.local/share/powershell/Modules/Logging/4.0.3/private/Start-LoggingManager.ps1:19 char:5
+     $initialState.ApartmentState = 'MTA'
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (:) [], RuntimeException
+ FullyQualifiedErrorId : PropertyAssignmentException
```
in **Start-LoggingManager.ps1** @ Line 18
```sh
    $initialState = [InitialSessionState]::CreateDefault()
    if($PSEdition -eq 'Desktop') {
        $initialState.ApartmentState = 'MTA'
    }
```

**Comment by jasonchester** [comment]
since $PSEdition isn't available before PS 5.1 a better check might be to test the property itself...

```sh
if($initialState.ApartmentState) { $true } 
```

**Comment by tosoikea** [comment]
@EsOsO https://github.com/PowerShell/PowerShell/issues/6908. The created InitialSessionState should be MTA by default.

**Comment by EsOsO** [comment]
Ok, we should drop the ApartmentState assignment ad use deafult

**Comment by tosoikea** [comment]
Okay, after some testing it seems like this is not true for all PowerShell versions...
I would include the following code snippet.

```powershell
$initialState = [InitialSessionState]::CreateDefault()
if (Get-Member -InputObject $initialState -Name "ApartmentState" -MemberType Property) {
   $initialState = [System.Threading.ApartmentState]::MTA
}
```

**Comment by tosoikea** [comment]
@jasonchester There is a new version up for download, implementing the wanted check. Could you test the functionality for powershell core with the updated version?

**Comment by jasonchester** [comment]
@tosoikea this works on powershell core now...

one strange thing I noticed when running the sample code

```powershell
Set-LoggingDefaultLevel -Level 'WARNING'
Add-LoggingTarget -Name Console
Add-LoggingTarget -Name File -Configuration @{Path = 'C:\Temp\example_%{+%Y%m%d}.log'}

$Level = 'DEBUG', 'INFO', 'WARNING', 'ERROR'
foreach ($i in 1..100) {
    Write-Log -Level ($Level | Get-Random) -Message 'Message n. {0}' -Arguments $i
    Start-Sleep -Milliseconds (Get-Random -Min 100 -Max 1000)
}

Wait-Logging  
```

is that the system hung... i identified the issue as the path set here:
```powershelll
Add-LoggingTarget -Name File -Configuration @{Path = 'C:\Temp\example_%{+%Y%m%d}.log'}
``` 
was not valid on my mac but instead of displaying a meaningful error message, logging appears to hang. One suggestion i would have would be to validate creating a file when adding a target or at least trapping any errors when writing to a target.

Otherwise everything looked great, thanks for the help.

**Comment by jasonchester** [comment]
Disregard my previous comment, cannot reproduce.

I removed the random start-sleep and saw the errors displayed...
```powershell
[2019-05-22 13:19:35-04] [ERROR  ] Message n. 97
Out-File : Cannot find drive. A drive with the name 'C' does not exist.
At /Users/jason.chester/.local/share/powershell/Modules/Logging/4.1.1/targets/File.ps1:32 char:17
+         $Text | Out-File @Params
+                 ~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (C:String) [Out-File], DriveNotFoundException
+ FullyQualifiedErrorId : DriveNotFound,Microsoft.PowerShell.Commands.OutFileCommand
```
