### ISSUE TITLE
Incompatibility with ErrorAction=Stop and Set-StrictMode -Version 2.0

### ISSUE THREAD

**Issue by tosoikea** [EsOsO/Logging#56]
### Steps to reproduce
We run our automation modules with Set-StrictMode -Version 2.0 and ErrorActionPreference=Stop.
After multiple different calls to the logging consumer, single methods seem to be in an undefined state resulting in a terminating error.
![image](https://user-images.githubusercontent.com/35578078/57611709-baf7c680-7573-11e9-9f4c-7a98edbe1790.png)

Error arises from Replace-Token ($var).

### Changes to be applied
- Fix methods to never allow an undefined variable (inconsistency)
- Determine the exact reason behind the MethodNotFoundException resulting from terminating errors
- Rework Replace-Token

**Comment by EsOsO** [comment]
I got some similar issues (if my understanding of the error text is right ;) ) and I think it doesn't relate to Replace-Token or StrictMode (I don't use it) or terminating errors but to the way the runspace load the module itself. Trying to reproduce but no luck.

**Comment by EsOsO** [comment]
Should be fixed in 4.2.2; let me know otherwise
