### ISSUE TITLE
Send Message to Specific Target (Slack)

### ISSUE THREAD

**Issue by MCrank** [EsOsO/Logging#58]
Hello,

I have downloaded the latest version of the Logging module and it seems to have broken (or fixed 😛 ) the method I used (Issue #33).  Digging around it seems like most of the previous plumbing of the Logging.psm1 file has changed.  Anytime I use Write-Log now the message goes to all targets.  My goal is to send more verbose logs to File and send only major errors to slack, otherwise it gets very noisy in the slack channel.

Is there different way to achieve the same result with the newer versions?

Thank you

**Comment by EsOsO** [comment]
Hi @MCrank can you provide an example of the code you're having issue with?

**Comment by MCrank** [comment]
Sure thing.  Here is my Configuration:
```powershell
Set-LoggingDefaultLevel -Level $LogLevel
Add-LoggingLevel -Level 50 -LevelName SLACK
$ScriptName = [System.IO.Path]::GetFileNameWithoutExtension($MyInvocation.MyCommand.Name)

Add-LoggingTarget -Name File -Configuration @{
  Path = "$($PSScriptRoot)\Logs\$($env:COMPUTERNAME)_$($ScriptName)_%{+%Y%m%d}.log" 
}

Add-LoggingTarget -Name Slack -Configuration @{
  WebHook = "$env:NightlySlackURL"; 
  Level   = 'SLACK' 
}
```

So when I needed to send something critical that needs my attention to slack I would call it like this:

```powershell
Write-Log -Level 'SLACK' -Message "Critical message goes here"
```
This would write the message to the Log file and send the message to slack as well.  With the latest version my Write-Log statements would all get fired to the log and slack even when not targeting the `SLACK` logging level.

Otherwise I would just call Write-Log and set -Level to one of the default DEBUG, INFO, ERROR, etc to just output to the log file.

Here are the lines that used to handle this in `Logging.psm1`
https://github.com/EsOsO/Logging/blob/e62cd0b185588972bce7731c05aa9359effe456d/Logging/Logging.psm1#L102-L104

Oh and the version that I am using that works in this way is 2.7.2

**Comment by EsOsO** [comment]
Hi @MCrank, since the introductions of defaults target configurations, the default target level doesn't honor the `Set-LoggingDefaultLevel` (I'll open an issue about that).

Right now you have to explicitly set the target level in the `Add-LoggingTarget` otherwise it will be set to NOTSET.
