### ISSUE TITLE
Loglevel is ignored

### ISSUE THREAD

**Issue by thorstenkampe** [EsOsO/Logging#61]
```powershell
Add-LoggingTarget -Name Console
Set-LoggingDefaultLevel -Level WARNING
Write-Log -Level INFO -Message 'Test'
[2019-07-01 23:28:19+02] [INFO   ] Test
```

**Comment by embusalacchi** [comment]
I believe the default logging level only takes effect if you don't specify a logging level.  In your example you're setting it to -Level INFO ...

**Comment by EsOsO** [comment]
Ate the moment `Set-LoggingDefaultLevel` only applies to subsequent target definition not already configured targets.
Try:
```
Set-LoggingDefaultLevel -Level WARNING
Add-LoggingTarget -Name Console
Write-Log -Level INFO -Message 'Test'
```

**Comment by ZamElek** [comment]
Seems the bug still exists (Reproduced on PowerShell 5.1 (Windows 10 1903), PowerShell 6.2.2 (Ubuntu)):

PS /home/pavel> Get-Module Logging

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     4.2.2      Logging

PS /home/pavel> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.2.2
PSEdition                      Core
GitCommitId                    6.2.2
OS                             Linux 5.0.0-25-generic #26-Ubuntu SMP Thu Aug 1…
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

The script:

PS /home/pavel> ipmo Logging
PS /home/pavel> Set-LoggingDefaultLevel -Level WARNING
PS /home/pavel> Add-LoggingTarget -Name Console
PS /home/pavel> Write-Log -Level INFO -Message 'Test'
PS /home/pavel> [2019-08-19 23:11:34+03] [INFO   ] Test

The same result is on Windows 10 computer.
