### ISSUE TITLE
Exiting shell makes console hang

### ISSUE THREAD

**Issue by thorstenkampe** [EsOsO/Logging#62]
```powershell
Add-LoggingTarget -Name Console
exit
[Console hangs]
```

**Comment by embusalacchi** [comment]
I have seen this happen a few times.  That said, I don't think I've seen it happen when I add the Wait-Logging to the end.

**Comment by EsOsO** [comment]
Let me know if 4.2.2 resolve this issue

**Comment by thorstenkampe** [comment]
Sorry, no change

**Comment by EsOsO** [comment]
I'm unable to figure why exiting the console makes it hangs... Any clue will be appreciated

**Comment by paulharman** [comment]
I'm also seeing this and am using wait-logging

**Comment by pdavis-od** [comment]
I am having this issue as well. Happening on Windows and Linux

**Comment by pdavis-od** [comment]
> I am having this issue as well. Happening on Windows and Linux and I am using 'Wait-Logging'. Happens in both cases.

In trying to see if I can find where things broke down, I found that version 4.1.1 works as intended on both Windows and PS Core on Ubuntu 18.04. I will most likely be running with that one until a later version comes along that "fixes" things. I would love to be able to get in there and see if I can figure this one out, but time is my enemy :(

**Comment by EsOsO** [comment]
> but time is my enemy :(

I know that feeling too. 

I really don't know how to inspect this behavior; for me is not a big issue cause I load the module in the profile and keep using it until I close the Powerhell shell, so it not hangs.

What's your use case?

**Comment by pdavis-od** [comment]
I am executing cron jobs (Ubuntu Server 16.04/18.04) that call a PowerShell script to read redirected stderr output and format/send to Elastic Search
