### ISSUE TITLE
LoggingTarget Console not working as expected

### ISSUE THREAD

**Issue by lzinga** [EsOsO/Logging#66]
In the latest versions of this powershell logging library I am getting unexpected behavior.

```powershell
Install-Module Logging
Import-Module Logging

Add-LoggingTarget -Name Console
Add-LoggingTarget -Name File -Configuration @{
    Path = "C:/Temp/%{+%Y.%m.%d}.log"
    Append = $false
}

Write-Log "Test"
```

With the code above while running through the PowerShell ISE "Test" does not get logged into the console, however it does get logged into the File location. I went back a version and the same thing occurred, finally I went back to 4.1.1 and the above code was working as expected.

I am not sure if there has been a functional change, but it is not reflected in the wiki here on github.

**Comment by lzinga** [comment]
Another issue which I believe is in 4.1.1 and up is that the colors don't show up when running from ISE as well. It shows up when the script is ran manually.

**Comment by turturis** [comment]
I was running a early version in the 2.x range. I decided to try the upgrade to 4.1.1 and experienced the same thing. i went as far back as 2.10 and experienced the same thing.

I have been using Logging module in 40-50 different projects for 3+ years.

I thought it would be as easy as dropping in the new module(s) and directories for targets and such, but that is not the case.

**Comment by EsOsO** [comment]
I'm really sorry to hear that messages are lost on ISE. I'm inspecting the behavior without success.
I'll take some more time to try to work around the issue, if you find more insights let me know.
