### ISSUE TITLE
New line in body of Teams message

### ISSUE THREAD

**Issue by mitrov** [EsOsO/Logging#75]
Hi

How can I write a new line in the body of a Teams message?

No matter what I tried so far, I always ended up getting one long string in the body of the Teams message. Any ideas / suggestions?

Thanks

**Comment by jangins101** [comment]
@mitrov - I know this is an old issue, but I just submitted [PR 108](https://github.com/EsOsO/Logging/pull/108) that included some enhancement for the Teams target. It's not rolled into master at this point, but it allows for Markdown in the message, so you could accomplish new lines as well as a few other options described in the PR.

**Comment by mitrov** [comment]
Thanks @jangins101, I'll have a look at it.
