### ISSUE TITLE
Cannot process argument because the value of argument "validValues" is out of range

### ISSUE THREAD

**Issue by replicaJunction** [EsOsO/Logging#8]
The first time I call Add-LoggingTarget, I receive this sequence of errors:

```

New-Object : Exception calling ".ctor" with "1" argument(s): "Cannot process argument because the value of argument "validValues" is out of range. Change argument "validValues" to  a value that is
within range.
Parameter name: validValues
Actual value was System.String[]."
At C:\Program Files\WindowsPowerShell\Modules\Logging\2.4.3\Logging.psm1:321 char:33
+ ... Attribute = New-Object System.Management.Automation.ValidateSetAttrib ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [New-Object], MethodInvocationException
    + FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand

New-Object : Exception calling ".ctor" with "1" argument(s): "Cannot process argument because the value of argument "validValues" is out of range. Change argument "validValues" to  a value that is
within range.
Parameter name: validValues
Actual value was System.String[]."
At C:\Program Files\WindowsPowerShell\Modules\Logging\2.4.3\Logging.psm1:321 char:33
+ ... Attribute = New-Object System.Management.Automation.ValidateSetAttrib ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [New-Object], MethodInvocationException
    + FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand

Cannot index into a null array.
At C:\Program Files\WindowsPowerShell\Modules\Logging\2.4.3\Logging.psm1:302 char:13
+         if ($TargetConf.Configuration[$Conf] -and $Configuration[$Con ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray

```

Here's the relevant section of the script using this module:

```powershell
if (Import-Module -Name 'Logging' -ErrorAction SilentlyContinue -PassThru) {
    Set-LoggingDefaultLevel -Level INFO
    Add-LoggingTarget -Name Console -Configuration @{}
    Add-LoggingTarget -Name File -Configuration @{
        Path  = $logFile
    }
}
```

The script stack trace points to the third line in the above snippet (the first call to Add-LoggingTarget) as the line that caused this error.

The strange thing is that after receiving this error once, I can't replicate it - running exactly the same script does not generate the error. I'm wondering if it's some sort of load order issue.

Logging.psm1:321 is this line:

```powershell
$ValidateSetAttribute = New-Object System.Management.Automation.ValidateSetAttribute($LogTargets.Keys)
```

I've confirmed this issue using PowerShell 5.0 on Win7 x64 as well as PowerShell 4.0 on Server 2012R2.

Let me know if I can provide any additional info. Thanks for all the work on this!

**Comment by EsOsO** [comment]
Hi Joshua, thx for the feedback, I suspect the problem could be the empty
hash table in the first call to add-loggingtarget, try to call it only with
the Name parameter.

I will look into it asap

Massimo

**Comment by EsOsO** [comment]
@replicaJunction I'm inspecting the issue, atm I'm not able to reproduce it on a Windows 10 machine.

Could you please verify if there's the 'target' folder inside the module path?

**Comment by replicaJunction** [comment]
Yep, the target folder exists, and has Console, ElasticSearch, Email, File, and Slack PS1 files in it. If it matters, I installed the module from the PSGallery to Program Files.

**Comment by replicaJunction** [comment]
Okay, here's how I can consistently reproduce this:

1. Save the script below to a .ps1 file.
2. Open a new PowerShell window that does not load the Logging module by profile/default
3. Run the script file. The error occurs.
4. Run the script file again in the same PowerShell session. The error does not occur.

```powershell
# Script file contents
if (Import-Module -Name 'Logging' -ErrorAction SilentlyContinue -PassThru) {
    Add-LoggingTarget -Name Console -Configuration @{}
    Write-Log -Message "Hi" -Level INFO
}
```

Output from the first run:
```
PS> .\t.ps1
New-Object : Exception calling ".ctor" with "1" argument(s): "Cannot process argument because the value of argument "validValues" is out of range. Change argument "validValues" to  a value that is within range.
Parameter name: validValues
Actual value was System.String[]."
At C:\Program Files\WindowsPowerShell\Modules\Logging\2.4.3\Logging.psm1:321 char:33
+ ... Attribute = New-Object System.Management.Automation.ValidateSetAttrib ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [New-Object], MethodInvocationException
    + FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand

PS> [2017-03-10 13:39:13-06] [INFO   ] Hi
```

Output from the second run:
```
PS> .\t.ps1

PS> [2017-03-10 13:43:13-06] [INFO   ] Hi
```

(I realize Wait-Logging would fix the log text appearing after the script exited and returned to the PowerShell prompt, but I wanted to keep this example as simple as possible to limit the possible issues.)

**Comment by EsOsO** [comment]
Hi @replicaJunction, I'm now able to reproduce the issue, it seems related to module import.
While I'm inspecting the cause you can workaround by manually importing the module at the beginning of the script.

Thanks for your feedbacks

**Comment by replicaJunction** [comment]
Confirmed - the latest commit fixed my issues as well. Thank you very much!
