### ISSUE TITLE
Keep using semver

### ISSUE THREAD

**Issue by EsOsO** [EsOsO/Logging#88]
Right now the build process uses gitversion to keep module versioning automated.

**Comment by gahujipo** [comment]
Do you want to replace Gitversion by something else?

**Comment by EsOsO** [comment]
Not necessarily, I want to keep infer the module version by git commits and pr and not having to do manually.

**Comment by Tadas** [comment]
Isn't that automatically happening here? https://github.com/EsOsO/Logging/blob/aa99080271cf700a26273cb89f3b22a7a93d906f/build.psake.ps1#L119
`$SemVer` seems to be coming from running gitversion before the build takes place

**Comment by EsOsO** [comment]
Yes, I was writing down the requirements for the new build script. But you fixed it and now we don't need to rewrite it.

**Comment by Tadas** [comment]
While on the subject on pipeline improvements, I think it would be useful to create dev releases. Would make it easier to test changes while master would be more stable.

**Comment by EsOsO** [comment]
I agree, I'll work on it asap.
