### ISSUE TITLE
Writing extended ascii to text file

### ISSUE THREAD

**Issue by turturis** [EsOsO/Logging#9]
If I attempt to write this character "—" in the Write-Log function, it will send to console out properly.  however, it will output a "?" to the log file.

In my current logging function I am able to write that character.  EsOsO Logging solution is much more clean and elegant so I would like to use it in my project.

can you see any way around this?

**Comment by EsOsO** [comment]
Hi @turturis, thanks for the appreciation.

I think could be the file encoding, it defaults to `ascii`. Could you try to set it in the configuration:
```
> Add-LoggingTarget -Name File -Configuration @{Path='C:\tmp\log.txt'; Encoding='unicode'}
```

Let me know if it works.

**Comment by turturis** [comment]
that worked beautifully,  thank you!

for my knowledge, where are the encoding types defined?  I looked for different encoding types in the code and could not find them I only saw the reference to default ascii.


I used this for making a separator.  I added a function to your module I called 'Separator'

```
Function Separator {
  [CmdletBinding()]
  Param ([Parameter(Mandatory=$false)][int]$Length = 40,
         [Parameter(Mandatory=$false)][string]$Character = "—")
  for ($i=1; $i -le $Length; $i++) {
    $separator = $separator + $Character
  }
  return $separator
}
```

and I call it like

`Write-Log -Level INFO (Separator -Length 50)`

you can feel free to add it if you wish. its nothing fancy. no attribution necessary.

**Comment by EsOsO** [comment]
You can find the encoding type in Out-File cmdlet:
[https://docs.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Utility/Out-File?view=powershell-5.1#required-parameters](Out-File doc)

You could write the separator with less hassle, like this:
`Write-Log -Level INFO -Message ('-' * 50)`

**Comment by turturis** [comment]
is that separator line above built in already?

thank you for that and your help in this issue, btw.

**Comment by EsOsO** [comment]
Yes, it's a powershell built-in operation; you can multiply a string n times.

You're welcome, I'm happy you found useful my module.
